#!/usr/bin/env bash
# -e: stop on first failure -u: exit on first unset var -o: first pipefail
set -euo pipefail

# just one liner to get all my stuff into a box
git clone https://github.com/oneness/dotfiles ~/.dotfiles \
    && cd ~/.dotfiles && make setup && echo You are good to go!
