#!/bin/sh

set -e

# setup doas
su - root -c "echo 'permit persist keepenv kasim' > /etc/doas.conf"

# Disable xconsole and beep
su - root -c "sed -i 's/xconsole/#xconsole/' /etc/X11/xenodm/Xsetup_0"
su - root -c "echo 'xset b off' >> /etc/X11/xenodm/Xsetup_0"

# Clone or pull dotfiles repo
if [ -d ~/.dotfiles ]; then
	cd ~/.dotfiles
	git pull --ff-only
else
	git clone https://github.com/oneness/dotfiles ~/.dotfiles
fi

os=$([ -f /etc/os-release ] && grep ^ID= /etc/os-release | cut -d = -f 2 || echo `uname`)

echo $os

# pkg_info -mz > pkgs to keep installed pkgs up to date
if [ -f ~/.dotfiles/pkgs ] && echo $os | grep "OpenBSD"; then
    echo You are on OpenBSD. Installing pkgs...
    doas pkg_add -l ~/.dotfiles/pkgs
    echo Your pkgs are installed!
fi

# Make home accessible to no one except for me
chmod 700 ~

# setup fonts
if [ -d ~/.dotfiles/fonts ]; then
    mkdir -p ~/.local/share
    ln -sf ~/.dotfiles/fonts ~/.local/share/
    fc-cache -v
fi


# Symlink dotfiles
cd ~/.dotfiles
for f in .???*; do
	rm -f ~/$f
	if [ $f != ".git" ]; then
	   (cd ~/; ln -s .dotfiles/$f $f)
	fi
done

# setup background jobs using vdcron
doas ln -fs ~/.dotfiles/vdcron.conf /etc/vdcron.conf
