#+OPTIONS: timestamp:nil
#+OPTIONS: author:nil
#+ATTR_HTML: :style text-align:center
[[mailto:ktuman@acm.org][Email]]          [[https://github.com/oneness][Github]]          [[https://www.birkey.co][Blog]]

* Personal Statement
  I enjoy engineering information systems optimized for end user and
  developer productivity, which can only be achieved by being vigilant
  about keeping IT as simple as IT possibly can be. If you are into
  Clojure, Haskell or other Programming Languages that I should check
  out, drop me a line via ktuman at acm dot org.
  *Note: I am NOT currently available for hire and do NOT respond to third-party
  recruiters.*

* Work Experience
- *2016/02 - Present:* Owner of [[https://www.birkey.co][Birkey Consulting]]
  - Coaching, Mentoring and Leading Engineering teams to design,
    develop and deliver.

- *2018/11 - Present:* Principal Software Engineer [[https://tapclicks.com][TapClicks Inc]]
  - Led development on the Google Sheets product, enabling
    customers to see all of their cross-network marketing data in
    spreadsheets
  - Implemented high availability as well as improved monitoring and
    scalability for the Report product
  - Implemented automated PDF exports of scheduled reports
  - Tech Stack: Clojure, ClojureScript, Elixir/Phoenix, Ruby on Rails,
    PostgreSQL and All things AWS.

- *2017/02 - 2018/09:* Omnyway Inc
  - Senior Full Stack Clojure Engineer as an early member of core
    Engineering Team responsible for Core e-commerce platform and API
    development.
  - Tech Stack: Clojure/ClojureScript, PostgreSQL, Kafka, and All things AWS.

- *2012/08 - 2017/02:* Runa Inc (Acquired by Staples Inc as Staples Labs)
  - Started as Clojure Engineer. Promoted to Engineering Lead,
    Engineering Manager and Director of Engineering. Responsible for
    SLA critical web services such as recommendation system, shipping
    prediction engine, etc.
  - Tech Stack: Clojure (with some Java where performance is
    critical), PostgreSQL/Redis, RabbitMQ (replaced by Kafka), Protobuf, and All things AWS.

- *2011/08 - 2012/08:* The Climate Corporation
  - Java/Clojure Engineer as a member of Risk Management Team.
  - Tech Stack: Java (with Clojure sneaked in as jars), Thrift, and Spring/Hibernate.

- *2005/10 - 2011/08:* Kyocera Document Solution USA
  - Started as Software Engineer then promoted to Team
    Lead. Responsible for developing Web Application that manages IoT printer fleets.
  - Tech Stack: Java, Spring/Hibernate, PostgreSQL, and OSGi.

* Education
- Post Graduate Computer Science with Software Engineering focus at California State University East Bay - CSUEB.
