#+TITLE: Kasim Tuman
#+AUTHOR: [[mailto:ktuman@acm.org][ktuman@acm.org]] \textbar{} [[https://github.com/oneness][oneness@github]] \textbar{} [[https://www.birkey.co/resume/resume.pdf][http://www.birkey.co/about]]

* Summary
  Software craftsman loves solving challenging problems using
  functional paradigm. Prefer working with data intensive
  projects. Currently available for short/long term consulting
  only. Might consider full time remote engagement.
* Work Experience
- 2017/02 - 2018/09: Omnyway Inc
  - Senior Full Stack Clojure Engineer as an early member of core
    Engineering Team responsible for Core e-commerce platform and API
    development.
  - Tech Stack: Clojure/ClojureScript, PostgreSQL, Kafka, and All things AWS.
- 2012/08 - 2017/02: Runa Inc (Acquired by Staples Inc as Staples Labs)
  - Started as Clojure Engineer. Promoted to Engineering Lead,
    Engineering Manager and Director of Engineering. Responsible for
    SLA critical web services such as recommendation system, shipping
    prediction engine, etc.
  - Tech Stack: Clojure (with some Java where performance is
    critical), PostgreSQL/Redis, RabbitMQ (replaced by Kafka), Protobuf, and All things AWS.
- 2011/08 - 2012/08: The Climate Corporation
  - Java/Clojure Engineer as a member of Risk Management Team.
  - Tech Stack: Java (with Clojure sneaked in as jars), Thrift, and Spring/Hibernate.
- 2005/10 - 2011/08: Kyocera Document Solution USA
  - Started as Software Engineer then promoted to Team
    Lead. Responsible for developing Web Application that manages IoT printer fleets.
  - Tech Stack: Java, Spring/Hibernate, PostgreSQL, and OSGi.
* Education
- Post Graduate Computer Science with Software Engineering focus at California State University East Bay - CSUEB.
