#+title: Few notes on Strange Loop 2021
#+date: <2021-10-03 10:56>
#+description:
#+filetags: conference strange-loop

This year's Strange Loop was my 4th and it was as good as it has been
in the past. Now, I am back and would like to share notes that I have
taken during the conference along with few of my thoughts.

This year I decided only to bring my Remarkable 2 for note taking. I
attended 8 sessions and following are my notes that I took. Before I
share it here, I'd like to state a few thoughts I have about the
conference. As soon as I learned that Strange Loop was going to happen
this year, I knew I would want to attend. However, considering the
pendamic, I was a bit skeptical if it is really going to happen in
person. To my joy, it was going to be in person and I bought the
ticket as soon as it is available. The conference usually starts with
a welcome party in City Museam (You have to visit if you happen to be
in Saint Louis). I stayed a hotel near the Museam so I can walk to it.
I was pleased to see Alex and the team with badges ready to be handed
out at the City Museam. I thanked him for organizing this and I can
tell he is excited to be able to pull it off considering all the
changes they went through in terms of sessions, attendies and formats
such as offering both in person and online version. City Museam is
always fun to visit and always innovating as one of its placard's
says: "Always be building". The conference never dissappointed me so
far. The lunch and hallway conversations was always fun and jolts my
brain. The folks attending was always from very different backgounds
intersecting so many tech domain that is always great to hear them
sharing what they are working on. I met a guy who created a code
search/analysis tool during his vacation to automate a tedious manual
process at work so he can replace himself using software as he puts it
(BTW, that is kind folks you want to be working with in a team). I
also met few folks at lunch table and talked about various things such
as GC, Dynamic vs Static typing and few programming languages such as
Clojure, Rust, Go, Elixir and Haskell just to name a few. I also met
few Emacs's user and shared stories how we ended up sticking with
Emacs for various reasons. Hallway conversations covered topics such
as which laptop to buy next among them is the upgradable Framework
laptop, which OS to use (consensus is that OS X is getting really
painfull to keep up to date, Linux is great for work but Desktop is
still not there, Windows is getting better with WSL with native Linux
GUI app support etc), and what programming language will take over the
world (one person is convinced that it is going to be Rust and not all
agree though). As you can tell, it is just pure fun to listen and
chime in above never ending discussion :).


