#+title: OpenBSD 7 Xfce Desktop
#+date: <2022-01-29 12:58>
#+description: Steps to install Xfce desktop on OpenBSD
#+filetags: openbsd

I blogged previously about why one should use OpenBSD and this time I
would like to document steps to have a fully working Xfce Desktop with
default installation. My goal is to keep the changes minimal only to
absolutely required steps, nothing more nothing less. If you find
steps missing (or did not work as expected) or not necessary, please
drop me a line via k tuman at acm dot org so I can address and update
this blog if needed.

1. Download the img and make USB boot disk:
   #+begin_src shell
     curl -O https://cdn.openbsd.org/pub/OpenBSD/7.0/amd64/install70.img
     sudo dd if=~/Downloads/install70.img of=/path/to/usb
   #+end_src
2. Boot from USB disk. Press *I* and hit enter when you see the
   `Welcome to the OpenBSD/amd64 7.0 installation program.` and follow
   the prompt. It is pretty straightforward. Once it is done, just
   reboot, which will automatically downloads and installs needed
   firmwares for your laptop.
   --*NOTE:*-- You can select whole disk and auto layout if you are not
   sure. Using wired connection for network interface is highly recommended.
3. Once you login, switch to root account, add needed packages and
   needed configs like this:
   #+begin_src shell
     su  ## prompts for root password
     pkg_add xfce xfce-extras ## install xfce desktop
     sed -i 's/xconsole/#xconsole/' /etc/X11/xenodm/Xsetup_0 # no xconcole
     usermod -G operator <user name> # so you can use xfce to log out, reboot etc
     usermod -G wheel <user name> # so you can use doas
     echo "permit persist :wheel" >> /etc/doas.conf # doas = sudo
     rcctl enable messagebus ## enable dbus
     rcctl start messagebus ## start dbus
     rcctl enable apmd ## enable power daemon
     rcctl start apmd  ## start power daemon
     exit # switch to your user account
     echo "exec startxfce4" > ~/.xsession ## auto launchs xfce4 desktop
     doas reboot ## restart to have a xfce default desktop
   #+end_src

*Bonus Tips and Tricks*
- Your wifi most likely will just work. In case if you get unlucky,
  here is how you can get it working:
  #+begin_src shell
    doas ifconfig # lists all supported interfaces
    doas fw_update # to install missing driver for your card
    dmesg | grep pci | grep <wifi card model> # report if not supported
    doas ifconfig # again to check if your card listed
    doas ifconfig join <Wifi name> wpakey <password> # to join your wifi
    # Run following 2 lines if you want to auto join your wifi:
    doas echo "join wifiname wpakey password" >> /etc/hostname.<wificardname>
    doas echo "dhcp" >> /etc/hostname.<wificardname>
    doas sh /etc/netstart # to restart the network
    ping openbsd.org # to test your network
  #+end_src
- While default Xfce4 desktop is fully functional out of the box, I
  recommend following packages:
  #+begin_src shell
    doas pkg_add xfce4-power-manager xfce4-whiskermenu
    ln -s -f yourloginpics ~/.face # profile in whiskermenu and in lock screen
  #+end_src
  Add them to the panel and tweak them to your liking. One setting I
  highly recommend enabling following in `Window Manager Tweaks`:
  - [✓] *Hide title of windows when maximized*
   
